### ISSUE TITLE
New design patterns in different languages

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/design-patterns#12]
Just make PR with the design pattern implementation, language doesn't matter. Just follow the structure: https://github.com/ZoranPandovski/design-patterns#contribution

**Comment by cjlcarvalho** [comment]
I just added singleton implementation in C++: https://github.com/ZoranPandovski/design-patterns/pull/17

**Comment by XOptimistixX** [comment]
I added method chaining implementations in Java and Python.
