### ISSUE TITLE
Translate the java code of "Head First Design Patterns: A Brain-Friendly Guide" to python.

### ISSUE THREAD

**Issue by rebuild-123** [ZoranPandovski/design-patterns#438]
Hi, we saw that you provided a link to buy "Head First Design Patterns: A Brain-Friendly Guide" in the "Resources" section, but the book doesn't have good enough python code.
We have translated the java code of "Head First Design Patterns: A Brain-Friendly Guide" to python, if necessary, you can refer to our translation code, thanks.
link: https://github.com/rebuild-123/Python-Head-First-Design-Patterns
.
What are the differences between other Python version Head-First-Design-Patterns and ours?
     - We annotate the type of the code so that the code we translate is closer to the java version.
     - We named the files with the same name and path as the original.

**Comment by ZoranPandovski** [comment]
Hey @rebuild-123, thanks for this, I just saw it. Can you make a PR and add link to it
